//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhoneBookDBEntities : DbContext
    {
        public PhoneBookDBEntities()
            : base("name=PhoneBookDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPhoneBookApp> tblPhoneBookApps { get; set; }
    
        public virtual int usp_GetDetailsByLastName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetDetailsByLastName");
        }
    
        public virtual ObjectResult<usp_GetPhoneBookDetails_Result> usp_GetPhoneBookDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPhoneBookDetails_Result>("usp_GetPhoneBookDetails");
        }
    }
}
